---
- name: Kubernetes install
  hosts: servers
  gather_facts: true
  vars_files:
    vars/main.yml
  roles:
    # - lxhome.kubernetes.k3s
    - lxhome.kubernetes.k8s


# ansible-playbook -i inventory_k8s.ini main.yml -t k8s_full_install
